"""add job quality score/flags and job observations

Revision ID: b3c7f0a5e1d9
Revises: 9a1d3e7c2b6f
Create Date: 2026-08-18 01:00:00.000000
"""

import sqlalchemy as sa
from alembic import op

revision = "b3c7f0a5e1d9"
down_revision = "9a1d3e7c2b6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("quality_score", sa.Integer(), nullable=False, server_default="100"),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "quality_flags", sa.JSON(), nullable=False, server_default=sa.text("'[]'")
        ),
    )
    # server_default is kept (not dropped) since sqlite has no ALTER COLUMN
    # support for that; the ORM model's Python-side defaults already cover
    # every insert going forward regardless.
    op.create_table(
        "job_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_observations")
    op.drop_column("jobs", "quality_flags")
    op.drop_column("jobs", "quality_score")
    # ### end Alembic commands ###
