"""add job description column and company_briefs table

Revision ID: c4d8e2f6a0b3
Revises: b3c7f0a5e1d9
Create Date: 2026-08-18 02:00:00.000000
"""

import sqlalchemy as sa
from alembic import op

revision = "c4d8e2f6a0b3"
down_revision = "b3c7f0a5e1d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
    )
    op.create_table(
        "company_briefs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_briefs")
    op.drop_column("jobs", "description")
    # ### end Alembic commands ###
