"""add job deadline_at column and reminders_sent table

Revision ID: d1e5f9a3c7b2
Revises: c4d8e2f6a0b3
Create Date: 2026-08-18 03:00:00.000000
"""

import sqlalchemy as sa
from alembic import op

revision = "d1e5f9a3c7b2"
down_revision = "c4d8e2f6a0b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_table(
        "reminders_sent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "application_id", "channel", name="uq_reminders_application_channel"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reminders_sent")
    op.drop_column("jobs", "deadline_at")
    # ### end Alembic commands ###
