"""add job taxonomy and expiry

Revision ID: d77abf7eb0d0
Revises: f089ccdd558b
Create Date: 2026-08-16 15:00:00.000000
"""

import sqlalchemy as sa
from alembic import op

revision = "d77abf7eb0d0"
down_revision = "f089ccdd558b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("listing_type", sa.String(length=32), nullable=True)
    )
    op.add_column("jobs", sa.Column("work_mode", sa.String(length=32), nullable=True))
    op.add_column("jobs", sa.Column("pay_type", sa.String(length=32), nullable=True))
    op.add_column("jobs", sa.Column("duration_months", sa.Integer(), nullable=True))
    op.add_column("jobs", sa.Column("target_year", sa.String(length=16), nullable=True))
    op.add_column(
        "jobs", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "expires_at")
    op.drop_column("jobs", "target_year")
    op.drop_column("jobs", "duration_months")
    op.drop_column("jobs", "pay_type")
    op.drop_column("jobs", "work_mode")
    op.drop_column("jobs", "listing_type")
    # ### end Alembic commands ###
