"""add telegram chat id to users

Revision ID: f089ccdd558b
Revises: c3d27ba3ad13
Create Date: 2026-08-12 09:34:52.360623
"""

import sqlalchemy as sa
from alembic import op

revision = "f089ccdd558b"
down_revision = "c3d27ba3ad13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram_chat_id", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_chat_id")
    # ### end Alembic commands ###
